### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Ustimov** [Ustimov/2016_1_IOTA#16]
- [ ] после регистрации нужно сделать проверку session get
- [x] крутилка матчмейкинга
- [x] ввод даты рождения при регистрации
- [ ] подсветка новой карты на пару секунд после того как её положил другой игрок
- [x] возможность паса у игрока
- [x] нельзя положить новую карту на старую если она не джокер
- [ ] отображение очков полученных за этот ход
- [x] кнопка завершения хода
- [ ] отображение сообщения при завершении игры с очками и пометками если кто-то не дожил до конца игры, редирект на главную
- [ ] если кто-то по очкам в highscore попадает - тоже отметку надо сделать наверное в сообщении и конце игры
- [ ] кнопка выхода из игры с подтверждением
